const fs = require('fs');

const ukPath = 'research/src/locales/uk.json';
let uk = JSON.parse(fs.readFileSync(ukPath, 'utf8'));
uk.reviewGeneratedPlanDraft = "Переглянути драфт";
uk.planDraftReadyTitle = "Драфт плану готовий";
uk.planDraftReadyBody = "Перегляньте та підкоригуйте драфт плану, який AI сформував на основі інтерв’ю, цілі та брифу. Після збереження всі наступні розмови оцінюватимуться за цими задачами.";
fs.writeFileSync(ukPath, JSON.stringify(uk, null, 2) + '\n');

const enPath = 'research/src/locales/en.json';
let en = JSON.parse(fs.readFileSync(enPath, 'utf8'));
en.reviewGeneratedPlanDraft = "Review draft";
en.planDraftReadyTitle = "Plan draft is ready";
en.planDraftReadyBody = "Review and adjust the plan draft generated by AI from your interview, goal, and brief. Once saved, all future interviews will be evaluated against these tasks.";
fs.writeFileSync(enPath, JSON.stringify(en, null, 2) + '\n');

console.log('locales patched');
