import {
  Mail,
  MessageSquare,
  Phone,
  Share2,
  Store,
  Building2,
  Laptop,
  Search,
  Mic,
  Video,
  Calendar,
  CreditCard,
  Settings,
  Bell,
  MessageCircle,
  Heart,
  Star,
  TrendingUp,
  FileText,
  Lock,
  MessagesSquare,
  Globe,
  Clock,
  ListChecks,
  Lightbulb,
  Users,
  Trophy,
  ShoppingCart,
} from 'lucide-react'

export const ICONS_BY_ID = {
  mail: Mail,
  email: Mail,
  sms: MessageSquare,
  phone: Phone,
  social: Share2,
  store: Store,
  building: Building2,
  laptop: Laptop,
  search: Search,
  mic: Mic,
  video: Video,
  calendar: Calendar,
  creditcard: CreditCard,
  settings: Settings,
  bell: Bell,
  messagecircle: MessageCircle,
  heart: Heart,
  star: Star,
  trending: TrendingUp,
  file: FileText,
  lock: Lock,
  messages: MessagesSquare,
  globe: Globe,
  clock: Clock,
  checklist: ListChecks,
  lightbulb: Lightbulb,
  users: Users,
  trophy: Trophy,
  cart: ShoppingCart,
}

export const CHANNEL_ICON_OPTIONS = [
  { id: 'mail', label: 'Email' },
  { id: 'phone', label: 'Phone' },
  { id: 'sms', label: 'SMS' },
  { id: 'social', label: 'Social' },
  { id: 'store', label: 'In-Store' },
  { id: 'building', label: 'Office' },
  { id: 'laptop', label: 'Laptop' },
  { id: 'search', label: 'Search' },
  { id: 'mic', label: 'Microphone' },
  { id: 'video', label: 'Video' },
  { id: 'calendar', label: 'Calendar' },
  { id: 'creditcard', label: 'Card' },
  { id: 'settings', label: 'Settings' },
  { id: 'bell', label: 'Notification' },
  { id: 'messagecircle', label: 'Chat' },
  { id: 'heart', label: 'Heart' },
  { id: 'star', label: 'Star' },
  { id: 'trending', label: 'Analytics' },
  { id: 'file', label: 'Document' },
  { id: 'lock', label: 'Security' },
  { id: 'messages', label: 'Messages' },
  { id: 'globe', label: 'Web' },
  { id: 'clock', label: 'Time' },
  { id: 'checklist', label: 'Checklist' },
  { id: 'lightbulb', label: 'Idea' },
  { id: 'users', label: 'Users' },
  { id: 'trophy', label: 'Award' },
  { id: 'cart', label: 'Cart' },
]

export const DEFAULT_CHANNELS = [
  { id: 'email', label: 'Email', iconId: 'mail' },
  { id: 'sms', label: 'SMS', iconId: 'sms' },
  { id: 'phone', label: 'Phone', iconId: 'phone' },
  { id: 'social', label: 'Social Media', iconId: 'social' },
  { id: 'store', label: 'In-Store', iconId: 'store' },
]

export const CHANNEL_COLORS = [
  '#000000',
  '#16a34a',
  '#2563eb',
  '#7c3aed',
  '#ea580c',
  '#dc2626',
  '#0d9488',
  '#ca8a04',
]

export function getDefaultChannelDetails() {
  return DEFAULT_CHANNELS.map((ch) => ({
    id: ch.id,
    label: ch.label,
    iconId: ch.iconId || ch.id,
    color: undefined,
    link: '',
  }))
}
