import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { ErrorState } from './UI';

export default function StudyForm({ study, onSave, onCancel, busy, error, onReload }) {
  const { t } = useTranslation();
  const [values, setValues] = useState({ title: study?.title || '', goal: study?.goal || '', brief: study?.brief || '' });
  const change = (key) => (event) => setValues((old) => ({ ...old, [key]: event.target.value }));
  return <form onSubmit={(event) => { event.preventDefault(); onSave({ title: values.title.trim(), goal: values.goal.trim(), brief: values.brief.trim() || null }); }} className="space-y-6">{error && <ErrorState error={error} onRetry={error.status === 409 ? onReload : undefined} />}<label className="block"><span className="research-label">{t('research.studyTitle')}</span><input required maxLength={200} value={values.title} onChange={change('title')} placeholder={t('research.studyTitlePlaceholder')} className="research-field" data-testid="research-study-title" /></label><label className="block"><span className="research-label">{t('research.goal')}<span className="ml-2 text-orange-600">*</span></span><textarea required maxLength={4000} rows={3} value={values.goal} onChange={change('goal')} placeholder={t('research.goalPlaceholder')} className="research-field resize-y" data-testid="research-study-goal" /><span className="mt-2 block text-xs leading-5 text-slate-400">{t('research.goalHint')}</span></label><label className="block"><span className="research-label">{t('research.brief')}<span className="ml-2 text-xs font-normal text-slate-400">{t('research.optional')}</span></span><textarea rows={5} maxLength={20000} value={values.brief} onChange={change('brief')} placeholder={t('research.briefPlaceholder')} className="research-field resize-y" data-testid="research-study-brief" /><span className="mt-2 block text-xs leading-5 text-slate-400">{t('research.briefHint')}</span></label><div className="flex flex-wrap justify-end gap-3 border-t border-slate-200/70 pt-5"><button type="button" onClick={onCancel} disabled={busy} className="research-secondary">{t('research.cancel')}</button><button disabled={busy || !values.title.trim() || !values.goal.trim()} className="research-primary" data-testid="research-study-save">{t(busy ? 'research.saving' : study ? 'research.save' : 'research.createStudy')}</button></div></form>;
}
