const assert = require('node:assert/strict');
const { createHash } = require('node:crypto');
const { test } = require('node:test');
const {
    INTERVIEW_SUMMARY_PRESET_SECTIONS,
    INTERVIEW_SUMMARY_SECTION_ORDER,
    normalizeInterviewSummarySections,
    resolveInterviewSummaryRequest,
    buildInterviewSummaryPrompt,
    normalizeInterviewSummaryData,
    mergeInterviewSummarySections,
    getInterviewSystemState,
    withInterviewSystemState,
    buildInterviewSummarySystemState,
    cleanModelJson,
    formatInterviewSummaryTranscript,
    SummaryService,
    DEFAULT_SUMMARY_PROVIDER,
    DEFAULT_SUMMARY_MODEL,
} = require('../modules/interviews/summary');

// Synthetic interviews contain no customer data. Hashes below were captured
// from server/index.js before extraction, not generated by the module under test.
const TRANSCRIPTS = {
    uk: [
        { timestamp: '00:00', speaker: 'Модератор', text: 'Спробуйте знайти та замовити доставку.' },
        { timestamp: '00:10', speaker: 'Учасник', text: 'Адресу знайшов, але не розумію, де обрати час.' },
    ],
    en: [
        { timestamp: '00:00', speaker: 'Moderator', text: 'Please find and book a delivery.' },
        { timestamp: '00:10', speaker: 'Participant', text: 'I found the address, but cannot tell where to choose a time.' },
    ],
};
const BASELINE_PROMPT_HASHES = {
    "uk": {
        "full_analysis": "757d7a536ef012a0f5c24465a06b64b28e49adbc179b9abca2921b4e487fd19f",
        "quick_summary": "2e810414152a5f1ad78a4dc68cace6b5dc405fdae7841d63b8502dd87c1cdf01",
        "research_insights": "1dda251351fd5583c487ed171d82137e015c1dd44c54c0c154290365f5768b97",
        "journey_mapping": "1e3039e8b1494e57da122282ace7d8d979001fcec434da347cee8e954dd3746a",
        "jtbd_analysis": "9f0f4e95ace7327ece6893017c3f7921fddc28cfd77686078dff5b3631bf7055",
        "prototype_testing": "6a6b3b597fd7570d866f4100f880ea82bbaf11bc0e4b0d4ea758b8f67f89b312",
        "usability_findings": "3997ad63aace6b387b67185babde0ac910d48b59682bc652e100abaa0b8bcbbb",
        "product_opportunities": "1cbef8462f1be36ebda9473d325e04eb5333904b696f50acbe7e834a589983a8",
        "decision_ready_report": "d84b16217636dd91757a1ccc9b98212e0f16e5fe42a16c421d2fa20fa4cbc85e",
        "custom": "59f12572df8db7eeab1658a82ae187e9550194c2c4fccfeb554e3674b5574864"
    },
    "en": {
        "full_analysis": "87db82ea9444d972f3e2d571386071250a0ba5a4032f6521e284dec44e8e48a2",
        "quick_summary": "54932607a7433e9c1d6652465ca76485d2539b6d7dbde58ddd017e800240495b",
        "research_insights": "48cb17f208c713f133862451071cc31f85b0332555dd0be4442fc51a6ae930cf",
        "journey_mapping": "883fd3a98fb4200dc952454808241887b130cbf5a628d01a8f16b9610e052236",
        "jtbd_analysis": "76ff8d957d0cf2df1c5a18227fe6c2be9de9fa3a3caa89f0fb28dafaaf5ad58f",
        "prototype_testing": "589767844e4f91120e7d476c4b1f7c414cbfdafcd1b20012ca87ef3e8380ad30",
        "usability_findings": "5598360e8bd47d92068784a948c9d6b809b41dfcb8d4c65c0bb0d101551a7729",
        "product_opportunities": "68357d45dda4deefe454c4eff2d3018c795873a4b959a34bd3d7f2b47e37e33b",
        "decision_ready_report": "e002929a26734850f26542015275369ab4ae64ffff4649f401cdb9fdd442be69",
        "custom": "d2e258d196eb31ca5e383cbec8b39852b223454691f21334bc0c937f367e8544"
    }
};
const sha256 = (value) => createHash('sha256').update(value).digest('hex');

const EXPECTED_PRESETS = {
    full_analysis: ['summary', 'journeyDraft', 'jtbdProfile', 'forcesOfProgress', 'painPoints', 'momentsOfFriction', 'unmetNeeds', 'workarounds', 'opportunityAreas', 'strengths', 'quotes'],
    quick_summary: ['summary', 'painPoints', 'strengths', 'quotes'],
    research_insights: ['summary', 'painPoints', 'strengths', 'momentsOfFriction', 'unmetNeeds', 'workarounds', 'opportunityAreas', 'quotes'],
    journey_mapping: ['summary', 'journeyDraft', 'painPoints', 'strengths', 'momentsOfFriction', 'quotes'],
    jtbd_analysis: ['summary', 'jtbdProfile', 'forcesOfProgress', 'strengths', 'quotes'],
    prototype_testing: ['summary', 'testedProductContext', 'taskSuccess', 'whatWorked', 'whatDidNotWork', 'confusionsObjections', 'actionableRecommendations', 'quotes'],
    usability_findings: ['testedProductContext', 'taskSuccess', 'whatWorked', 'whatDidNotWork', 'confusionsObjections', 'quotes'],
    product_opportunities: ['summary', 'featureRequests', 'actionableRecommendations', 'quotes'],
    decision_ready_report: ['summary', 'testedProductContext', 'taskSuccess', 'whatWorked', 'whatDidNotWork', 'featureRequests', 'actionableRecommendations', 'quotes'],
};
const PROTOTYPE_PRESETS = new Set(['prototype_testing', 'usability_findings', 'product_opportunities', 'decision_ready_report']);
const CUSTOM_REQUEST = { selectedSections: [' quotes ', 'summary', 'taskSuccess', 'quotes', 'unknown', 42] };

test('all existing presets preserve sections, order, mode and default merge behavior', () => {
    assert.deepEqual(INTERVIEW_SUMMARY_PRESET_SECTIONS, EXPECTED_PRESETS);
    for (const [preset, selectedSections] of Object.entries(EXPECTED_PRESETS)) {
        assert.deepEqual(resolveInterviewSummaryRequest({ preset }), {
            preset,
            selectedSections,
            analysisMode: PROTOTYPE_PRESETS.has(preset) ? 'prototype_testing' : 'service_design',
            mergeMode: 'merge_selected',
        });
    }
    for (const body of [undefined, null, {}, { preset: 'unknown' }, { selectedSections: ['unknown', 42] }]) {
        assert.deepEqual(resolveInterviewSummaryRequest(body), resolveInterviewSummaryRequest({ preset: 'full_analysis' }));
    }
});

test('custom section selection retains caller order, removes duplicates and infers prototype mode', () => {
    assert.deepEqual(resolveInterviewSummaryRequest(CUSTOM_REQUEST), {
        preset: 'custom',
        analysisMode: 'prototype_testing',
        selectedSections: ['quotes', 'summary', 'taskSuccess'],
        mergeMode: 'merge_selected',
    });
    assert.deepEqual(normalizeInterviewSummarySections('summary'), []);
    assert.deepEqual(resolveInterviewSummaryRequest({
        preset: ' quick_summary ', selectedSections: ['taskSuccess'], analysisMode: ' service_design ', mergeMode: 'replace_all',
    }), {
        preset: 'quick_summary', analysisMode: 'service_design', selectedSections: ['taskSuccess'], mergeMode: 'replace_all',
    });
    assert.equal(resolveInterviewSummaryRequest({ preset: 'quick_summary', selectedSections: ['taskSuccess'] }).analysisMode, 'service_design');
    assert.equal(resolveInterviewSummaryRequest({ analysisMode: 'unknown', mergeMode: 'REPLACE_ALL' }).mergeMode, 'merge_selected');
    assert.deepEqual(resolveInterviewSummaryRequest({ selectedSections: ['summary'] }).selectedSections, ['summary']);
});

test('every UA/EN preset and custom prompt is byte-for-byte equivalent to the original pipeline', () => {
    for (const [locale, transcript] of Object.entries(TRANSCRIPTS)) {
        const conversationText = formatInterviewSummaryTranscript(transcript);
        assert.equal(conversationText, transcript.map(line => `[${line.timestamp}] ${line.speaker}: ${line.text}`).join('\n'));
        for (const preset of [...Object.keys(EXPECTED_PRESETS), 'custom']) {
            const request = resolveInterviewSummaryRequest(preset === 'custom' ? CUSTOM_REQUEST : { preset });
            const prompt = buildInterviewSummaryPrompt({ conversationText, ...request });
            assert.equal(sha256(prompt), BASELINE_PROMPT_HASHES[locale][preset], `${locale}/${preset} prompt changed`);
            assert.ok(prompt.includes('Detect the dominant language of the transcript and write the entire output in that exact same language.'));
            assert.ok(prompt.includes('Base every conclusion only on evidence from the transcript.'));
            assert.ok(prompt.endsWith(`Transcript:\n"""\n${conversationText}\n"""`));
        }
    }
});

const LEGACY_RESPONSE = {
    jobToBeDone: ' Book a delivery ', generalInsights: ' The time selector is unclear. ', overallSentiment: ' MIXED ',
    journeyDraft: { jobContext: ' At home ', stages: [{
        stage: ' Booking ', customerActions: [' Select address ', '', 5], drivers: [' Convenience '],
        touchpoints: [' Home screen ', { actor: ' Courier ', channel: ' App ' }],
        painPoints: [' Delay ', { problem: ' No time slots ', severity: ' HIGH ' }],
    }] },
    jtbdProfile: { mainJob: ' Plan delivery ', functionalJob: ' Choose a time ', emotionalJob: ' Feel certain ', socialJob: '', jobContext: ' Busy day ', desiredOutcome: ' Receive the parcel ', successCriteria: [' On time '] },
    forcesOfProgress: { pushes: [' Failed booking '], pulls: [' Flexible time '], anxieties: [' Missing parcel '], habits: [' Calling support '] },
    painPoints: [' Confusing icon ', { title: ' Time ', painPoint: ' Hidden ', rootCause: ' Weak label ', impact: ' Failed booking ', severity: ' HIGH ', quote: ' Where is the time? ' }],
    momentsOfFriction: [{ stage: ' Booking ', situation: ' Choosing time ', breakdown: ' No control ', customerReaction: ' Hesitation ' }],
    unmetNeeds: [' Certainty ', { need: ' Flexibility ', whyItMatters: ' Work hours ' }],
    workarounds: [' Phone call ', { workaround: ' Ask a friend ', whatItSignals: ' Need for help ' }],
    opportunityAreas: [' Scheduling ', { area: ' Labels ', rationale: ' Reduce confusion ' }],
    strengths: [' Address lookup ', { title: ' Fast search ', description: ' Found address ', whyItWorks: ' Familiar ', quote: ' Easy ' }],
    testedProductContext: { prototype: ' Delivery flow ', scenario: ' Book delivery ', goal: ' Observe scheduling ', audience: ' Recipient ' },
    taskSuccess: [{ task: ' Choose slot ', outcome: ' PARTIAL ', observation: ' Found day ', quote: ' I found it ' }],
    whatWorked: [' Search ', { title: ' Address ', reason: ' Recognizable ', quote: ' Clear ' }],
    whatDidNotWork: [' Schedule ', { title: ' Slots ', description: ' Hidden ', impact: ' Blocked ', quote: ' Cannot find it ' }],
    confusionsObjections: [{ stage: ' Time ', objection: ' Missing slot ', cause: ' Label ', quote: ' Where? ' }],
    featureRequests: [' Calendar ', { feature: ' Reminders ', need: ' Certainty ', quote: ' Remind me ' }],
    actionableRecommendations: [' Label selector ', { action: ' Show slots ', reason: ' Discoverability ', priority: ' HIGH ' }],
    quotes: [' Where is the time? ', '', 42, ' Search is easy ', ' I need reminders ', ' Extra quote '],
    _system: { transcription: { provider: 'legacy' } }, unknownField: 'ignored',
};
const LEGACY_EXPECTED = {
    "summary": {
        "jobToBeDone": "Book a delivery",
        "generalInsight": "The time selector is unclear.",
        "overallSentiment": "mixed"
    },
    "journeyDraft": {
        "jobContext": "At home",
        "stages": [
            {
                "stage": "Booking",
                "customerActions": [
                    "Select address"
                ],
                "drivers": [
                    "Convenience"
                ],
                "touchpoints": [
                    {
                        "touchpoint": "Home screen",
                        "interactsWith": "",
                        "channel": ""
                    },
                    {
                        "touchpoint": "",
                        "interactsWith": "Courier",
                        "channel": "App"
                    }
                ],
                "painPoints": [
                    {
                        "title": "",
                        "description": "Delay",
                        "severity": ""
                    },
                    {
                        "title": "",
                        "description": "No time slots",
                        "severity": "high"
                    }
                ]
            }
        ]
    },
    "jtbdProfile": {
        "mainJob": "Plan delivery",
        "functionalJob": "Choose a time",
        "emotionalJob": "Feel certain",
        "socialJob": "",
        "jobContext": "Busy day",
        "desiredOutcome": "Receive the parcel",
        "successCriteria": [
            "On time"
        ]
    },
    "forcesOfProgress": {
        "pushes": [
            "Failed booking"
        ],
        "pulls": [
            "Flexible time"
        ],
        "anxieties": [
            "Missing parcel"
        ],
        "habits": [
            "Calling support"
        ]
    },
    "painPoints": [
        {
            "title": "",
            "description": "Confusing icon",
            "rootCause": "",
            "impact": "",
            "severity": "",
            "evidenceQuote": ""
        },
        {
            "title": "Time",
            "description": "Hidden",
            "rootCause": "Weak label",
            "impact": "Failed booking",
            "severity": "high",
            "evidenceQuote": "Where is the time?"
        }
    ],
    "momentsOfFriction": [
        {
            "stage": "Booking",
            "situation": "Choosing time",
            "breakdown": "No control",
            "customerReaction": "Hesitation"
        }
    ],
    "unmetNeeds": [
        {
            "need": "Certainty",
            "whyItMatters": ""
        },
        {
            "need": "Flexibility",
            "whyItMatters": "Work hours"
        }
    ],
    "workarounds": [
        {
            "workaround": "Phone call",
            "whatItSignals": ""
        },
        {
            "workaround": "Ask a friend",
            "whatItSignals": "Need for help"
        }
    ],
    "opportunityAreas": [
        {
            "area": "Scheduling",
            "rationale": ""
        },
        {
            "area": "Labels",
            "rationale": "Reduce confusion"
        }
    ],
    "strengths": [
        {
            "title": "Address lookup",
            "description": "",
            "whyItWorks": "",
            "evidenceQuote": ""
        },
        {
            "title": "Fast search",
            "description": "Found address",
            "whyItWorks": "Familiar",
            "evidenceQuote": "Easy"
        }
    ],
    "testedProductContext": {
        "productOrPrototype": "Delivery flow",
        "testedScenario": "Book delivery",
        "researchGoal": "Observe scheduling",
        "targetUser": "Recipient"
    },
    "taskSuccess": [
        {
            "task": "Choose slot",
            "outcome": "partial",
            "whatHappened": "Found day",
            "evidenceQuote": "I found it"
        }
    ],
    "whatWorked": [
        {
            "item": "Search",
            "whyItWorked": "",
            "evidenceQuote": ""
        },
        {
            "item": "Address",
            "whyItWorked": "Recognizable",
            "evidenceQuote": "Clear"
        }
    ],
    "whatDidNotWork": [
        {
            "item": "Schedule",
            "problem": "",
            "impact": "",
            "evidenceQuote": ""
        },
        {
            "item": "Slots",
            "problem": "Hidden",
            "impact": "Blocked",
            "evidenceQuote": "Cannot find it"
        }
    ],
    "confusionsObjections": [
        {
            "moment": "Time",
            "confusionOrObjection": "Missing slot",
            "likelyCause": "Label",
            "evidenceQuote": "Where?"
        }
    ],
    "featureRequests": [
        {
            "request": "Calendar",
            "underlyingNeed": "",
            "evidenceQuote": ""
        },
        {
            "request": "Reminders",
            "underlyingNeed": "Certainty",
            "evidenceQuote": "Remind me"
        }
    ],
    "actionableRecommendations": [
        {
            "recommendation": "Label selector",
            "rationale": "",
            "priority": ""
        },
        {
            "recommendation": "Show slots",
            "rationale": "Discoverability",
            "priority": "high"
        }
    ],
    "quotes": [
        "Where is the time?",
        "Search is easy",
        "I need reminders"
    ]
};

test('legacy aliases, section shapes, enums, trimming and empty defaults stay compatible', () => {
    assert.deepEqual(normalizeInterviewSummaryData(LEGACY_RESPONSE), LEGACY_EXPECTED);
    assert.equal(normalizeInterviewSummaryData(LEGACY_RESPONSE)._system, undefined);
    assert.equal(normalizeInterviewSummaryData(LEGACY_RESPONSE).unknownField, undefined);
    for (const raw of [null, undefined, [], 'summary', 42, {}, { _system: { status: 'done' } }, { unknown: 'data' }]) {
        assert.equal(normalizeInterviewSummaryData(raw), null);
    }
    const minimal = normalizeInterviewSummaryData({ summary: { generalInsight: 'Корисний висновок.' } });
    assert.equal(minimal.summary.generalInsight, 'Корисний висновок.');
    assert.equal(minimal.summary.overallSentiment, '');
    assert.deepEqual(minimal.taskSuccess, []);
    assert.deepEqual(minimal.testedProductContext, { productOrPrototype: '', testedScenario: '', researchGoal: '', targetUser: '' });
});

test('malformed entries are ignored and section size limits remain stable', () => {
    const many = (value) => [null, [], 99, ...Array.from({ length: 12 }, () => value)];
    const normalized = normalizeInterviewSummaryData({
        painPoints: many(' Problem '), taskSuccess: many({ task: 'T', outcome: 'UNSUPPORTED' }),
        workarounds: many(' Alternative '), quotes: many(' Quote '),
        journeyDraft: { stages: many({ stage: 'S', customerActions: many('A'), drivers: many('D'), touchpoints: many('Touchpoint'), painPoints: many('P') }) },
        jtbdProfile: { successCriteria: many('Success') }, forcesOfProgress: { pushes: many('Push') },
    });
    assert.equal(normalized.painPoints.length, 5);
    assert.equal(normalized.taskSuccess.length, 6);
    assert.equal(normalized.taskSuccess[0].outcome, '');
    assert.equal(normalized.workarounds.length, 3);
    assert.equal(normalized.quotes.length, 3);
    assert.equal(normalized.journeyDraft.stages.length, 8);
    assert.equal(normalized.journeyDraft.stages[0].customerActions.length, 6);
    assert.equal(normalized.journeyDraft.stages[0].drivers.length, 5);
    assert.equal(normalized.journeyDraft.stages[0].touchpoints.length, 6);
    assert.equal(normalized.journeyDraft.stages[0].painPoints.length, 5);
    assert.equal(normalized.jtbdProfile.successCriteria.length, 5);
    assert.equal(normalized.forcesOfProgress.pushes.length, 5);
});

test('selected-section merge preserves existing sections including when selected output is empty', () => {
    const previous = { summary: { generalInsight: 'Keep this' }, painPoints: ['Old pain'], quotes: ['Old quote'], _system: { transcription: { provider: 'openai' } } };
    const generated = normalizeInterviewSummaryData({ painPoints: ['New pain'] });
    const before = JSON.stringify(previous);
    const merged = mergeInterviewSummarySections(previous, generated, ['painPoints', 'quotes']);
    assert.equal(merged.summary.generalInsight, 'Keep this');
    assert.equal(merged.painPoints[0].description, 'New pain');
    assert.deepEqual(merged.quotes, []);
    assert.equal(JSON.stringify(previous), before);
    assert.deepEqual(mergeInterviewSummarySections(null, generated, ['painPoints']), generated);
    assert.deepEqual(Object.keys(merged), Object.keys(LEGACY_EXPECTED));
    assert.deepEqual(new Set(Object.keys(merged)), new Set(INTERVIEW_SUMMARY_SECTION_ORDER));
});

test('system state survives summary replacement and does not mutate saved data', () => {
    const existing = { summary: { generalInsight: 'Original' }, _system: { transcription: { provider: 'openai' }, status: 'ready' } };
    const state = buildInterviewSummarySystemState(getInterviewSystemState(existing), {
        provider: 'gemini', model: 'gemini-2.5-pro', ...resolveInterviewSummaryRequest({ preset: 'prototype_testing' }),
    });
    assert.deepEqual(state.transcription, { provider: 'openai' });
    assert.equal(state.status, 'ready');
    assert.ok(Number.isFinite(Date.parse(state.summaryGeneration.generatedAt)));
    assert.equal(existing._system.summaryGeneration, undefined);
    assert.deepEqual(withInterviewSystemState(existing, {}), { summary: { generalInsight: 'Original' } });
    assert.equal(getInterviewSystemState(withInterviewSystemState(null, state)), state);
    for (const value of [null, [], { _system: [] }, { _system: 'bad' }]) assert.deepEqual(getInterviewSystemState(value), {});
});

test('provider JSON cleanup keeps fenced and surrounding-prose compatibility', () => {
    for (const text of ['{"quotes":["Good"]}', '```json\n{"quotes":["Good"]}\n```', '```\n{"quotes":["Good"]}\n```', 'Result:\n{"quotes":["Good"]}\nDone']) {
        assert.deepEqual(JSON.parse(cleanModelJson(text)), { quotes: ['Good'] });
    }
    assert.equal(cleanModelJson(null), '');
    assert.equal(cleanModelJson(' no JSON '), 'no JSON');
});

test('SummaryService uses the original model, prompt and merge flow with an injected provider', async () => {
    const calls = [];
    const service = new SummaryService({ generateText: async (prompt) => {
        calls.push(prompt);
        return '```json\n{"summary":{"generalInsight":"Час доставки знайти складно."},"taskSuccess":[{"task":"Обрати час","outcome":"partial"}]}\n```';
    } });
    const oldSummary = { summary: { generalInsight: 'Старий висновок' }, strengths: ['Зручний пошук адреси'], _system: { transcription: { provider: 'openai' }, status: 'done' } };
    const original = JSON.stringify(oldSummary);
    const result = await service.generate({ transcriptData: TRANSCRIPTS.uk, existingSummaryData: oldSummary, request: { preset: 'prototype_testing' } });
    assert.equal(calls.length, 1);
    assert.equal(sha256(calls[0]), BASELINE_PROMPT_HASHES.uk.prototype_testing);
    assert.equal(DEFAULT_SUMMARY_PROVIDER, 'gemini');
    assert.equal(DEFAULT_SUMMARY_MODEL, 'gemini-2.5-pro');
    assert.equal(result.summary.generalInsight, 'Час доставки знайти складно.');
    assert.equal(result.strengths[0].title, 'Зручний пошук адреси');
    assert.equal(result.taskSuccess[0].outcome, 'partial');
    assert.deepEqual(result._system.transcription, { provider: 'openai' });
    assert.equal(result._system.status, 'done');
    const { generatedAt, ...generation } = result._system.summaryGeneration;
    assert.ok(Number.isFinite(Date.parse(generatedAt)));
    assert.deepEqual(generation, { provider: 'gemini', model: 'gemini-2.5-pro', ...resolveInterviewSummaryRequest({ preset: 'prototype_testing' }) });
    assert.equal(JSON.stringify(oldSummary), original);
});

test('replace_all clears old analysis but preserves transcription metadata', async () => {
    const service = new SummaryService({ generateText: async () => '{"quotes":["New quote"]}' });
    const result = await service.generate({
        transcriptData: TRANSCRIPTS.en,
        existingSummaryData: { painPoints: ['Old pain'], _system: { transcription: { estimatedCostUsd: 0.01 } } },
        request: { selectedSections: ['quotes'], mergeMode: 'replace_all' },
    });
    assert.deepEqual(result.quotes, ['New quote']);
    assert.deepEqual(result.painPoints, []);
    assert.deepEqual(result._system.transcription, { estimatedCostUsd: 0.01 });
    assert.equal(result._system.summaryGeneration.mergeMode, 'replace_all');
});

test('invalid/empty provider output and provider failures retain existing failure semantics', async () => {
    const args = { transcriptData: TRANSCRIPTS.en };
    const invalidResponses = [];
    const invalid = new SummaryService({ generateText: async () => 'not JSON', onInvalidResponse: (text) => invalidResponses.push(text) });
    await assert.rejects(invalid.generate(args), { message: 'AI returned an invalid response format.' });
    assert.deepEqual(invalidResponses, ['not JSON']);
    for (const output of ['{}', 'null', '[]', '{"_system":{"status":"done"}}']) {
        const empty = new SummaryService({ generateText: async () => output });
        await assert.rejects(empty.generate(args), { message: 'AI returned an empty or unsupported summary format.' });
    }
    const providerError = new Error('Provider unavailable');
    const failing = new SummaryService({ generateText: async () => { throw providerError; } });
    await assert.rejects(failing.generate(args), (error) => error === providerError);
    assert.throws(() => new SummaryService({}), /requires a generateText function/);
});
